version: '3.6'

services:
  kong-database:
    image: cassandra
    volumes:
      - ./cassandra_db:/var/lib/cassandra
    restart: always

  kong:
    depends_on:
      - kong-database
    image: kong:latest
    restart: always
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:8001:8001
