version: '3.7'

services:
  kong-database:
    image: cassandra:3.0
    container_name: kong-database
    restart: always
    volumes:
      - ./cassandra_db:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  migrations:
    depends_on:
      - kong-database
    image: kong:latest
    container_name: kong-migrations
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    command: kong migrations bootstrap -vv

  kong:
    depends_on:
      - kong-database
    image: kong:latest
    container_name: kong
    restart: always
    environment:
      - KONG_DATABASE= cassandra
      - KONG_CASSANDRA_CONTACT_POINTS= kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_NGINX_HTTP_RESOLVER=8.8.8.8
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
      - KONG_REAL_IP_RECURSIVE=on

    ports:
      - 127.0.0.1:80:8000
      - 127.0.0.1:8001:8001
